# Discord Bot Configuration
discord:
  bot_token: "your_discord_bot_token_here"
  prefix: "!"
  description: "Claude Code Discord Bot"

# Claude Code Configuration
claude_code:
  api_key: "your_anthropic_api_key_here"
  # api_url: "https://api.anthropic.com"

# Bot Settings
bot:
  system_prompt: "You are a helpful agent in a Discord server."
  max_turns: 2
  # You can specify tools that the bot is allowed to use.
  # allowed_tools:
  #   - Bash(date)

# Error Messages
messages:
  empty_message: "Please provide a message. What would you like to ask?"
  general_error: "An error occurred. Please try again later."
  empty_response: "No response received from Claude."

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"