version: '3.8'

services:
  discord-bot:
    build: .
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    container_name: claude-discord-bot
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge